export default {
  // 400
  BAD_REQUEST: 'BAD_REQUEST',

  // 401
  UNAUTHORIZED: 'UNAUTHORIZED',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  INVALID_AUTH_TOKEN: 'INVALID_AUTH_TOKEN',

  // 403
  FORBIDDEN: 'FORBIDDEN',

  // 404
  NOT_FOUND: 'NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACADEMY_NOT_FOUND: 'ACADEMY_NOT_FOUND',
  COURT_NOT_FOUND: 'COURT_NOT_FOUND',

  // 409
  CONFLICT: 'CONFLICT',

  // 500
  ERROR: 'INTERNAL_SERVER_ERROR',
};
