export default {
  STAFF_ENABLED: 'staff_enabled',
  STAFF_LIMIT: 'staff_limit',
  PLAYERS_ENABLED: 'players_enabled',
  PLAYERS_LIMIT: 'players_limit',
  ACADEMIES_ENABLED: 'academies_enabled',
  ACADEMIES_LIMIT: 'academies_limit',
  COURTS_ENABLED: 'courts_enabled',
  COURTS_LIMIT: 'courts_limit',
  BOOKINGS_ENABLED: 'bookings_enabled',
  TOURNAMENTS_ENABLED: 'tournaments_enabled',
  TOURNAMENTS_LIMIT: 'tournaments_limit',
  REPORTS_ENABLED: 'reports_enabled',
  EVENTS_ENABLED: 'events_enabled',
  EVENTS_LIMIT: 'events_limit',
  INVENTORY_ENABLED: 'inventory_enabled',
  NEWS_ENABLED: 'news_enabled',
  COMMUNITY_FORUMS_ENABLED: 'community_forums_enabled',
};
